### ISSUE TITLE
Failed to activate the refactor package

### ISSUE THREAD

**Issue by maksimr** [hax/refactor#1]
[Enter steps to reproduce below:]
1. install plugin
2. open editor

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [refactor](https://github.com/hax/refactor) package, v0.5.1
### Stack Trace

Failed to activate the refactor package

```
At undefined is not a function

TypeError: undefined is not a function
  at new ModuleManager (/home/maksimrv/.atom/packages/refactor/lib/module_manager.coffee:20:20)
  at Main.module.exports.Main.activate (/home/maksimrv/.atom/packages/refactor/lib/refactor.coffee:21:22)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
  at /usr/share/atom/resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:306:60
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -0:37.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
refactor, v0.5.1
vim-surround, v0.7.2

# Dev
No dev packages
```

**Comment by hax** [comment]
You need also install language plugins. Currently [JavaScript plugin](https://atom.io/packages/js-refactor) and [CoffeeScript plugin](https://atom.io/packages/coffee-refactor) is available.

**Comment by maksimr** [comment]
@hax Thanks
