### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by xpeH** [hax/refactor#15]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [refactor](https://github.com/hax/refactor) package, v0.6.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /C:/Users/Artur/.atom/packages/refactor/lib/refactor.coffee:102

TypeError: Cannot read property 'length' of undefined
    at Main.module.exports.Main.onDone (C:\Users\Artur\.atom\packages\refactor\lib\refactor.coffee:70:5)
    at atom-text-editor.<anonymous> (C:\Users\Artur\.atom\packages\refactor\lib\refactor.coffee:1:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Artur\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Artur\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Artur\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Artur\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Artur\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Artur\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
  3x -8:13.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:58.2.0 command-palette:toggle (div.package-detail.panels-item)
     -6:53.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -6:51.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -6:50.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:50.3.0 settings-view:show-keybindings (div.package-detail.panels-item)
     -6:46.3.0 window:reload (atom-text-editor.editor.mini.is-focused)
     -6:39.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -5:48.6.0 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:40.3.0 core:close (atom-text-editor.editor.is-focused)
  3x -0:43.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:32.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:28.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:07.1.0 refactor:done (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.19
column-select, v0.2.0
javascript-standard-snippets, v0.2.1
js-refactor, v0.6.0
minimap, v4.18.1
refactor, v0.6.0

# Dev
No dev packages
```

**Comment by Redsandro** [comment]
`refactor-js` also stopped working for me. I believe it was after I installed [toggle-quotes](https://github.com/atom/toggle-quotes) and `seti-ui`. Not sure if that's relevant.

**Comment by hax** [comment]
Pls try the lateset version. If still problem, just reopen this issue.

**Comment by gidztech** [comment]
This issue is occurring for me. I just installed `refactor` and `js-refactor` and when I run the shortcut I get this same error message.

**Comment by hax** [comment]
@gidztech Could you provide the code which trigger the error? Thank you.

**Comment by gidztech** [comment]
@hax The strange thing is that I just tried it again with the same script I was working on yesterday and it works fine now. I can't explain it though. Maybe a reboot of my computer did something.
