### ISSUE TITLE
Uncaught TypeError: ref.dispose is not a function

### ISSUE THREAD

**Issue by livelazily** [hax/refactor#32]
[Enter steps to reproduce below:]

1. Just close a file tab

**Atom Version**: 1.12.4
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [refactor](https://github.com/hax/refactor) package, v0.11.0

### Stack Trace

Uncaught TypeError: ref.dispose is not a function

```
At /Users/livelazily/.atom/packages/refactor/lib/watcher.coffee:59

TypeError: ref.dispose is not a function
    at Watcher.module.exports.Watcher.deactivate (/Users/livelazily/.atom/packages/refactor/lib/watcher.coffee:59:14)
    at Watcher.module.exports.Watcher.dispose (/Users/livelazily/.atom/packages/refactor/lib/watcher.coffee:15:6)
    at Watcher.dispose (/Users/livelazily/.atom/packages/refactor/lib/watcher.coffee:1:1)
    at /Users/livelazily/.atom/packages/refactor/lib/refactor.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:534:27)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:645:18)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:690:19)
```

### Commands

```
     -6:34.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -6:31.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -6:31.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:28.9.0 pane:show-previous-item (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -4:03.9.0 core:copy (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -4:02.1.0 tree-view:reveal-active-file (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:53.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:52.8.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:52.1.0 refactor:done (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:52.1.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:52.1.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:51.2.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:50.9.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -3:49.5.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:30.3.0 core:copy (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  3x -0:27.6.0 core:close (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "support-gbk",
      "atom-backbone",
      "atom-backbone",
      "nuclide-hg-repository",
      "nuclide-click-to-symbol",
      "nuclide-file-watcher",
      "nuclide-flow",
      "nuclide-hack",
      "nuclide-language-hack",
      "nuclide-remote-projects",
      "nuclide-ocaml",
      "nuclide-blame-provider-hg",
      "nuclide-buck-files",
      "nuclide-debugger-hhvm",
      "turbo-javascript",
      "spell-check",
      "vim-surround",
      "pigments",
      "line-diff-details"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet",
      "bookmarks"
    ],
    "telemetryConsent": "no",
    "useCustomTitleBar": true,
    "warnOnLargeFileLimit": 2
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
angularjs, v0.3.5 (active)
angularjs-styleguide-snippets, v0.9.1 (active)
atom-backbone, v0.6.1 (inactive)
atom-beautify, v0.29.13 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-ternjs, v0.16.1 (active)
atom-typescript, v10.1.12 (active)
auto-detect-indentation, v1.3.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-python, v1.8.12 (inactive)
chester-atom-syntax, v0.1.1 (inactive)
docblockr, v0.8.7 (active)
dracula-theme, v1.2.8 (inactive)
editorconfig, v2.0.5 (active)
emmet, v2.4.3 (active)
esformatter, v2.0.1 (active)
ex-mode, v0.13.1 (inactive)
file-icons, v1.7.25 (active)
genesis-syntax, v1.0.7 (inactive)
genesis-ui, v0.5.0 (inactive)
git-diff-details, v1.4.0 (active)
git-plus, v5.25.3 (active)
highlight-selected, v0.11.2 (active)
indent-guide-improved, v1.4.11 (active)
indentation-indicator, v1.0.0 (active)
js-refactor, v0.7.3 (active)
jumpy, v3.1.3 (inactive)
language-gradle, v0.0.3 (active)
language-groovy, v0.6.0 (active)
last-cursor-position, v0.9.0 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-eslint, v8.0.0 (active)
linter-htmlhint, v1.3.1 (active)
linter-scss-lint, v3.0.4 (active)
local-history, v3.4.1 (active)
minimap, v4.25.6 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
monokai, v0.18.0 (inactive)
pigments, v0.37.0 (inactive)
project-manager, v3.3.3 (active)
python-tools, v0.6.8 (active)
refactor, v0.11.0 (active)
relative-numbers, v0.5.1 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
split-diff, v1.0.6 (inactive)
sync-settings, v0.7.2 (active)
tab-switcher, v1.5.4 (active)
turbo-javascript, v1.4.0 (inactive)
vim-mode, v0.65.1 (active)
vim-surround, v0.8.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by mutsys** [comment]
Ditto:

**Atom version**: 1.12.4
**refactor version**: 0.11.0
**macOS version**: 10.12.1

```
TypeError: ref.dispose is not a function
    at Watcher.module.exports.Watcher.deactivate (/Users/mrose/.atom/packages/refactor/lib/watcher.coffee:59:14)
    at Watcher.module.exports.Watcher.dispose (/Users/mrose/.atom/packages/refactor/lib/watcher.coffee:15:6)
    at Watcher.dispose (/Users/mrose/.atom/packages/refactor/lib/watcher.coffee:1:1)
    at /Users/mrose/.atom/packages/refactor/lib/refactor.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:534:27)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:645:18)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:711:17)
```

**Comment by netsi1964** [comment]
After I updated refactor package I now have a new problem: [https://github.com/hax/refactor/issues/33](https://github.com/hax/refactor/issues/33)
