### ISSUE TITLE
Uncaught TypeError: this.ripper.dispose is not a function

### ISSUE THREAD

**Issue by yaplas** [hax/refactor#33]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.4
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [refactor](https://github.com/hax/refactor) package, v0.11.1

### Stack Trace

Uncaught TypeError: this.ripper.dispose is not a function

```
At /Users/agustin/.atom/packages/refactor/lib/watcher.coffee:54

TypeError: this.ripper.dispose is not a function
    at Watcher.module.exports.Watcher.deactivate (/Users/agustin/.atom/packages/refactor/lib/watcher.coffee:54:15)
    at Watcher.module.exports.Watcher.dispose (/Users/agustin/.atom/packages/refactor/lib/watcher.coffee:15:6)
    at Watcher.dispose (/Users/agustin/.atom/packages/refactor/lib/watcher.coffee:1:1)
    at /Users/agustin/.atom/packages/refactor/lib/refactor.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:534:27)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:645:18)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:711:17)
```

### Commands

```
     -0:45.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-html-preview, v0.1.22 (active)
atom-terminal, v0.8.0 (inactive)
atom-typescript, v8.9.1 (active)
editorconfig, v2.0.5 (active)
emmet, v2.4.3 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
js-refactor, v0.7.3 (active)
language-babel, v2.49.2 (active)
language-docker, v1.1.7 (active)
linter, v1.11.4 (active)
linter-docker, v0.1.2 (active)
linter-eslint, v8.0.0 (active)
linter-sass-lint, v1.7.4 (active)
minimap, v4.25.6 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
node-debugger, v1.5.0 (active)
preview, v0.17.0 (inactive)
refactor, v0.11.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by devmi** [comment]
Same issue

Atom Version: 1.12.4
Thrown From: refactor package, v0.11.1

## Stack Trace

```
Uncaught TypeError: this.ripper.dispose is not a function

/Users/devmi/.atom/packages/refactor/lib/watcher.coffee:54

TypeError: this.ripper.dispose is not a function
    at Watcher.module.exports.Watcher.deactivate (/Users/devmi/.atom/packages/refactor/lib/watcher.coffee:54:15)
    at Watcher.module.exports.Watcher.dispose (/Users/devmi/.atom/packages/refactor/lib/watcher.coffee:15:6)
    at Watcher.dispose (/Users/devmi/.atom/packages/refactor/lib/watcher.coffee:1:1)
    at /Users/devmi/.atom/packages/refactor/lib/refactor.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:534:27)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:645:18)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:711:17)

```

**Comment by patkirts** [comment]
Same issue, when I close any atom tab.
Atom 1.12.4, refactor 0.11.1

**Comment by zaaack** [comment]
Same here.

**Comment by mikeerickson** [comment]
Here is what I am receiving (seems to be hungup on the coffee watcher, which I am not even using

![image](https://cloud.githubusercontent.com/assets/183153/20457534/7a811714-ae42-11e6-9ef3-a4736d4d8ff4.png)

**Comment by zaaack** [comment]
The right fixup should be `@ripper?.dispose?()` in https://github.com/hax/refactor/commit/c12c4fa820578e0ae0c31580f542c0ab1d6adaeb#diff-916ed9ff3af024bb3f86b2b51b79b5c4L59

**Comment by IceOnFire** [comment]
I edited the code by hand and the fix works. Shall we open a pull request?

**Comment by hax** [comment]
PR is welcome :)

**Comment by IceOnFire** [comment]
https://github.com/hax/refactor/pull/35 locked and loaded!

**Comment by mschipperheyn** [comment]
Let's merge this one! This issue is a nightmare!

**Comment by IceOnFire** [comment]
@hax, are you there?

**Comment by mattiascaricato** [comment]
merge plz :3

**Comment by steebchen** [comment]
Edited it manually weeks ago, was incredibly annoying.
