### ISSUE TITLE
TypeError: _ref.dispose is not a function

### ISSUE THREAD

**Issue by zaaack** [hax/refactor#34]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [refactor](https://github.com/hax/refactor) package, v0.11.0

### Stack Trace

Uncaught TypeError: _ref.dispose is not a function

```
At /Users/z/.atom/packages/refactor/lib/watcher.coffee:59

TypeError: _ref.dispose is not a function
  at Watcher.module.exports.Watcher.deactivate (/Users/z/.atom/packages/refactor/lib/watcher.coffee:59:14)
  at Watcher.module.exports.Watcher.dispose (/Users/z/.atom/packages/refactor/lib/watcher.coffee:15:6)
  at Watcher.dispose (/Users/z/.atom/packages/refactor/lib/watcher.coffee:1:1)
  at /Users/z/.atom/packages/refactor/lib/refactor.coffee:37:17
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:529:27)
  at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:645:18)
  at atom-tabs.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:325:26)
  at atom-tabs.TabBarView.closeAllTabs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:456:28)
  at Object.addElementCommands.tabs:close-all-tabs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:120:26)
  at atom-tabs.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:86:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1133:28)
  at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:354:25)
  at emitThree (events.js:110:13)
  at EventEmitter.emit (events.js:188:7)

```

### Commands

```
     -0:37.6.0 command-palette:toggle (atom-pane.pane.active)
     -0:34 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:34 project-plus:toggle-project-finder (atom-pane.pane.active)
     -0:21.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.3.0 tabs:close-all-tabs (li.texteditor.tab.sortable.right-clicked)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "jshint",
      "AtomicChar",
      "Remote-FTP",
      "remote-sync",
      "random-tips",
      "random-tips",
      "python-tools",
      "tasks",
      "markdown-preview-plus",
      "show-in-system",
      "linter-scss-lint",
      "editor-background",
      "global-background",
      "linter-flow-plus",
      "linter-flake8",
      "hyperclick",
      "tool-bar",
      "tree-ignore",
      "atom-react-autocomplete",
      "react",
      "highlight-selected",
      "atom-sync",
      "git-status",
      "source-preview-react",
      "terminal-plus",
      "random-tips",
      "linter",
      "project-manager",
      "markdown-preview",
      "markdown-scroll-sync",
      "atom-image-resize",
      "standardjs-snippets",
      "tree-view",
      "qolor",
      "atom-typescript"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".DS_Store",
      "*.pyc",
      "venv"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.alm, vundefined (inactive)
activate-power-mode, v1.1.0 (active)
atom-beautify, v0.29.13 (inactive)
atom-handlebars, v1.3.0 (active)
atom-image-resize, v0.3.0 (inactive)
atom-jade, v0.3.0 (active)
atom-react-autocomplete, v0.1.10 (inactive)
atom-sync, v0.7.3 (inactive)
atom-ternjs, v0.16.1 (active)
atom-typescript, v10.1.12 (inactive)
atomic-chrome, v0.3.0 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-nunjucks, v0.5.0 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-python, v1.8.12 (active)
ava, v0.8.0 (inactive)
browser-plus, v0.0.86 (active)
color-picker, v2.2.3 (active)
docblockr, v0.8.7 (active)
editorconfig, v2.0.5 (active)
elastic-tabstops, v1.1.2 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.25 (active)
git-status, v0.3.4 (inactive)
git-time-machine, v1.5.4 (inactive)
glist, v2.2.0 (inactive)
global-background, v0.4.0 (inactive)
hex, v0.6.2 (active)
js-hyperclick, v1.9.0 (active)
js-refactor, v0.7.3 (active)
jumpy, v3.1.3 (inactive)
language-babel, v2.48.4 (active)
language-json5, v1.1.0 (active)
language-nunjucks, v4.1.0 (active)
linter, v1.11.16 (inactive)
linter-eslint, v8.0.0 (active)
linter-handlebars, v2.3.4 (active)
linter-pug-lint, v0.2.0 (active)
linter-stylelint, v3.5.0 (active)
local-history, v3.4.1 (active)
markdown-preview-enhanced, v0.8.9 (active)
markdown-scroll-sync, v2.1.2 (inactive)
markdown-writer, v2.6.2 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.6 (active)
minimap-autohide, v0.10.1 (active)
node-debugger, v1.9.1 (active)
nuclide, v0.181.0 (active)
pigments, v0.37.0 (active)
platformio-ide-terminal, v2.2.2 (active)
project-manager, v3.2.3 (inactive)
project-plus, v0.9.0 (active)
prompt-big-file, v0.3.0 (active)
python-tools, v0.6.8 (inactive)
qolor, v0.4.1 (inactive)
quick-highlight, v0.6.1 (active)
react-snippets, v0.5.0 (active)
refactor, v0.11.0 (active)
regex-railroad-diagram, v0.16.0 (active)
Remote-FTP, v0.8.3 (inactive)
remote-sync, v4.1.2 (inactive)
rest-client, v1.3.1 (active)
script, v3.11.1 (inactive)
source-preview, v0.5.0 (inactive)
source-preview-pug, v0.2.0 (active)
source-preview-react, v0.2.0 (inactive)
source-preview-sass, v0.1.6 (active)
standardjs-snippets, v2.4.0 (inactive)
sync-settings, v0.7.2 (active)
terminal-plus, v0.14.5 (inactive)
tnote, v0.2.0 (inactive)
todo-show, v1.8.0 (inactive)
toggle-slash, v1.0.14 (active)
tool-bar, v1.0.1 (inactive)
tree-ignore, v0.6.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (active)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by zaaack** [comment]
https://github.com/hax/refactor/issues/33
