### ISSUE TITLE
Uncaught TypeError: Cannot read property 'delete' of null

### ISSUE THREAD

**Issue by jozolr** [hax/refactor#43]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [refactor](https://github.com/hax/refactor) package 0.11.3

### Stack Trace

Uncaught TypeError: Cannot read property 'delete' of null

```
At C:\Users\JP4097\.atom\packages\refactor\lib\refactor.coffee:36

TypeError: Cannot read property 'delete' of null
    at /packages/refactor/lib/refactor.coffee:36:18
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.destroyed (/app.asar/src/text-editor.js:551:20)
    at TextEditor.module.exports.Model.destroy (/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:660:18)
    at Pane.module.exports.Pane.destroyActiveItem (/app.asar/src/pane.js:638:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/app.asar/src/workspace.js:701:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/app.asar/src/workspace.js:740:21)
    at /app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -8:16.2.0 core:save (input.hidden-input)
     -8:09.5.0 editor:consolidate-selections (input.hidden-input)
     -8:09.5.0 core:cancel (input.hidden-input)
     -4:02.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
  9x -3:09.2.0 core:move-left (input.hidden-input)
  3x -3:07.8.0 core:move-right (input.hidden-input)
     -2:59.3.0 core:move-left (input.hidden-input)
     -2:58.9.0 core:move-down (input.hidden-input)
     -2:58.3.0 core:move-up (input.hidden-input)
  9x -2:58.1.0 core:move-right (input.hidden-input)
     -2:56.8.0 core:move-left (input.hidden-input)
     -2:44.8.0 core:backspace (input.hidden-input)
  3x -1:10.8.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
highlight-selected 0.12.0 
js-refactor 0.7.5 
open-recent 5.0.0 
pigments 0.39.0 
refactor 0.11.3 
```

**Comment by morgzz** [comment]
I ran into this problem today with refactor 0.11.3 installed. I ended up disabling it due to the depreciation cop yelling at me that it has been depreciated. When I'd close a tab it would pop up with the mentioned error. Just exit Atom and restart; it shouldn't error again of course assuming you've disabled the package.
